import { useState } from "react";
import { useNavigate } from 'react-router-dom';

const senjata = [
  /* ASSAULT RIFLES */
  { name: 'SS3-M1 10.5"', 
    description: "5,56 mm gas operated assault rifle for Law Enforcement and Military use specifically designed and tuned to operate even on the harshest condition. Suitable for Designated Marksman Rifle (DMR) roles within a combat unit.", 
    image: "SS3-M1 10.5.png",
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated, Piston",
      EmptyWeight: "3,18 kg",
      OverallLength: "770 mm",
      BarrelLength: "10,5”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "200 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: 'SS3-M1 14.5"', 
    description: "5,56 mm gas operated carbine for Military and Law Enforcement use conditions. WEAPONSspecifically designed and tuned to operate even on the most challenging", 
    image: "SS3-M1 14.5.png",
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated, Piston",
      EmptyWeight: "3,25 kg",
      OverallLength: "871 mm",
      BarrelLength: "14,5”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: 'SS3-M1 16"', 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use conditions.  specifically designed and tuned to operate even on the most challenging challenging conditions.", 
    image: "SS3-M1 16.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated, Piston",
      EmptyWeight: "3,40 kg",
      OverallLength: "909 mm",
      BarrelLength: "16”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "350 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: 'SS3-M1 20"', 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use specifically designed and tuned to operate even on the most challenging conditions. Suitable for DMR role within a combat unit ", 
    image: "SS3-M1 20.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated, Piston",
      EmptyWeight: "3,65 kg",
      OverallLength: "1001 mm",
      BarrelLength: "20”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V1", 
    description: "5,56 mm gas operated assault rifle for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions.", 
    image: "SS2-V1.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,95 kg",
      OverallLength: "985 mm",
      BarrelLength: "460 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V1 A1", 
    description: " 5,56 mm gas operated assault rifle for Military and Law Enforcement use tested and qualified on the most demanding battlefield conditions. Additional picatinny rail and adjustable buttstock provide better modularity and ergonomy ", 
    image: "SS2-V1 A1.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas ",
      EmptyWeight: "4,02 kg",
      OverallLength: "1018 mm",
      BarrelLength: "460 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V1 HB", 
    description: "5,56 mm gas operated assault rifle with Heavy Barrel for excellent accuracy and precision.", 
    image: "SS2-V1 HB.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,55 kg",
      OverallLength: "989 mm",
      BarrelLength: "460 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minutes",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V2", 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use, tested, and qualified on the most demanding battlefield conditions.", 
    image: "SS2-V2.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,82 kg",
      OverallLength: "930 mm",
      BarrelLength: "403 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minutes",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V2 A1", 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions. Additional picatinny rail and adjustable buttstock provide better modularity and ergonomy.", 
    image: "SS2-V2 A1.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,68 kg",
      OverallLength: "960 mm",
      BarrelLength: "403 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V2 A2", 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions. Additional picatinny rail and adjustable buttstock provide better modularity and ergonomy.", 
    image: "SS2-V2 A2.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,45 kg",
      OverallLength: "960 mm",
      BarrelLength: "403 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V2 HB", 
    description: " 5,56 mm gas operated carbine with Heavy Barrel for excellent accuracy and precision.", 
    image: "SS2-V2 HB.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,23 kg",
      OverallLength: "932 mm",
      BarrelLength: "403 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V4", 
    description: " 5,56 mm gas operated assault rifle for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions. Suitable for DMR role within a combat unit.", 
    image: "SS2-V4.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,45 kg",
      OverallLength: "1.024 mm",
      BarrelLength: "500 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V4 HB", 
    description: " 5,56 mm gas operated assault rifle with Heavy Barrel for excellent accuracy and precision.", 
    image: "SS2-V4 HB.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,84 kg",
      OverallLength: "1.026 mm",
      BarrelLength: "500 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V4 A1", 
    description: " 5,56 mm gas operated assault rifle for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions. Additional picatinny rail and adjustable buttstock provide better modularity and ergonomy. ", 
    image: "SS2-V4 A1.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,28 kg",
      OverallLength: "1.055 mm",
      BarrelLength: "500 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V4 A2", 
    description: " 5,56 mm gas operated carbine for Military and Law Enforcement use, tested and qualified on the most demanding battlefield conditions. Additional MLOK rail and adjustable buttstock provide advanced modularity and ergonomy.", 
    image: "SS2-V4 A2.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "4,05 kg",
      OverallLength: "1.055 mm",
      BarrelLength: "500 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "400 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V5", 
    description: "5,56 mm gas operated short-barreled assault rifle for Military and Law Enforcement use tested and qualified on the most demanding battlefield conditions. Suitable for armoured vehicle and artillery crews.", 
    image: "SS2-V5.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,35 kg",
      OverallLength: "750 mm",
      BarrelLength: "255 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "200 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minutes",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS2-V5 A1", 
    description: " 5,56 mm gas operated short-barreled assault rifle for Military and Law Enforcement use tested and qualified on the most demanding battlefield conditions. Suitable for close quarter battle scenarios.", 
    image: "SS2-V5 A1.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,62 kg",
      OverallLength: "800 mm",
      BarrelLength: "255 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "200 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS AMPHIBIOUS", 
    description: " 5,56 mm gas operated amphibious assault rifle for amphibious operations. The rifle can be operated seamlessly between land and underwater operations simply by changing the magazine loaded with underwater ammunition and switching the gas lever to underwater setting. ", 
    image: "SS AMPHIBIOUS.png", 
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "-Above Water : 30 rounds -Under Water : 20 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,4 kg",
      OverallLength: "795 mm",
      BarrelLength: "10,5”",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "-Above Water : 200 m -Under Water : 12 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "-Above Water : Safe, Single, Automatic -Under Water : Safe, Single",
    },
  },

  { name: "SS DOPPER", 
    description: " 7,62 mm gas operated battle rifle for military training. The rifle, when used with special Dopper ammunition, provides loud sound while maintaining safety (no ricochet) when fired to the soil.", 
    image: "SS DOPPER.png", 
    specifications: {
      Caliber: "7,62 x 51 mm",
      MagazineCapacity: "20 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "5,3 kg",
      OverallLength: "1.060 mm",
      BarrelLength: "460 mm",
      Sight: "Adjustable Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "300 m",
      Rifling: "304,8 mm/Twist",
      FiringMode: "Safe, Semi Automatic",
    },
  },

  { name: "SS BLACKOUT-V1", 
    description: " .300 Blackout gas operated assault rifle for Military and Law Enforcement use, designed based on the successful SS2 platform. Additional MLOK rail and adjustable buttstock provide advanced modularity and ergonomy.", 
    image: "SS BLACKOUT-V1.png", 
    specifications: {
      Caliber: ".300 Blackout (7,62 x 35 mm)",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,8 kg",
      BarrelLength: "16”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "460 m",
      RateOfFire: "720 - 820 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS BLACKOUT-V2", 
    description: "300 Blackout gas operated short-barreled assault rifle for Military and Law Enforcement use designed based on the successful SS2 platform. Additional MLOK rail and adjustable buttstock provide advanced modularity and ergonomy. ", 
    image: "SS BLACKOUT-V2.png", 
    specifications: {
      Caliber: ".300 Blackout (7,62 x 35 mm)",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,5 kg",
      BarrelLength: "10,5”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "200 m",
      RateOfFire: "720 - 820 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SS BLACKOUT-V3", 
    description: "300 Blackout gas operated short-barreled assault rifle for Military and Law Enforcement use designed based on the successful SS2 platform. Additional MLOK rail and adjustable buttstock provide advanced modularity and ergonomy. ", 
    image: "SS BLACKOUT-V3.png", 
    specifications: {
      Caliber: ".300 Blackout (7,62 x 35 mm)",
      MagazineCapacity: "30 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,2 kg",
      BarrelLength: "7,5”",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "100 m",
      RateOfFire: "720 - 820 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },


  /* PISTOL */
  { name: "G2 COMBAT", 
    description: "9 mm pistol suitable for standard service-use by military and Law Enforcements", 
    image: "G2 COMBAT.png",
    specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "15 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "0,93 kg",
      OverallLength: "202 mm",
      BarrelLength: "4,5”",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 250 mm/twist",
    },
  },

  { name: "PISTOL G2 COMBAT A1", 
    description: " 9 mm pistol suitable for tactical-use by military and Law Enforcements.", 
    image: "PISTOL G2 COMBAT A1.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "15 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "0,94 kg",
      OverallLength: "202 mm",
      BarrelLength: "114,3 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 250 mm/twist",
      Rail: "Picatinny Rail / MIL-STD-1913",
    },
  },

  { name: "G2 ELITE", 
    description: " 9 mm pistol suitable for standard service-use by military and Law Enforcements.", 
    image: "G2 ELITE.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "15 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "1 kg",
      OverallLength: "223 mm",
      BarrelLength: "5”",
      Sight: "Fixed Front & Adjustable Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 250 mm/twist",
    },
  },

  { name: "G2 PREMIUM", 
    description: " 9 mm pistol crafted to win shooting competitions.", 
    image: "G2 PREMIUM.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "17 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "1, 05 kg",
      OverallLength: "222 mm",
      BarrelLength: "5”",
      Sight: "Fixed Front & Adjustable Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 250 mm/twist",
    },
  },

  { name: "MAG-4", 
    description: " 9 mm pistol with 4 inch barrel designed for Military and Law Enforcements use.", 
    image: "MAG-4.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "15 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "0,91 kg",
      OverallLength: "193 mm",
      BarrelLength: "4”",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "15 m",
    },
  },

  { name: "P3A", 
    description: " 7,65 x 17 mm (.32 ACP) pistol designed for self defence.", 
    image: "P3A.png",
     specifications: {
      Caliber: "7,65 x 17 mm (.32 ACP)",
      MagazineCapacity: "12 rounds",
      FiringMode: "Semi Automatic",
      Action: "Double Action",
      Weight: "0,794 kg",
      OverallLength: "180 mm",
      BarrelLength: "102 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Hammer Lock",
      EffectiveRange: "15 m",
    },
  },

  { name: "FIRST DEFENCE", 
    description: " 9 x 21 mm pistol based on 1911 platform, designed for concealed carry and self-defence.", 
    image: "FIRST DEFENCE.png",
     specifications: {
      Caliber: "9 x 21 mm",
      MagazineCapacity: "8 rounds",
      FiringMode: "Semi Automatic",
      Action: "Single Action",
      Weight: "0,95 kg",
      OverallLength: "180 mm",
      BarrelLength: "87 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Manual Lever",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 250 mm/twist",
    },
  },

  { name: "ARMO V1", 
    description: " 9 mm polymer-framed pistol designed for Military and Law Enforcement use.", 
    image: "ARMO V1.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "16 rounds",
      FiringMode: "Semi Automatic",
      Action: "Double Action",
      Weight: "0,78 kg",
      OverallLength: "189 mm",
      BarrelLength: "98 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Firing Pin Safety & Manual Safety",
      EffectiveRange: "25 m",
      FrameMaterial: "Polymer",
    },
  },

  { name: "ARMO V2", 
    description: " 9 mm polymer-framed pistol designed for Military and Law Enforcement use.", 
    image: "ARMO V2.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "16 rounds",
      FiringMode: "Semi Automatic",
      Action: "Double Action",
      Weight: "0,85 kg",
      OverallLength: "209 mm",
      BarrelLength: "118 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Firing Pin Safety & Manual Safety",
      EffectiveRange: "25 m",
      FrameMaterial: "Polymer",
    },
  },

  { name: "ARMO V3", 
    description: " 9 mm polymer-framed pistol designed for Military and Law Enforcement use.", 
    image: "ARMO V3.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "16 rounds",
      FiringMode: "Semi Automatic",
      Action: "Double Action",
      Weight: "0,89 kg",
      OverallLength: "221 mm",
      BarrelLength: "127 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Firing Pin Safety & Manual Safety",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 254 mm/twist",
      FrameMaterial: "Polymer",
    },
  },

  { name: "ARMO V3 IPSC", 
    description: " 9 mm polymer-framed pistol specially built and tuned for shooting competitions..", 
    image: "ARMO V3 IPSC.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "16 rounds",
      FiringMode: "Semi Automatic",
      Action: "Double Action",
      Weight: "0,89 kg",
      OverallLength: "212 mm",
      BarrelLength: "112 mm",
      Sight: "Phosphorus Dot Fixed Front & Adjustable Rear Sight",
      Safety: "Firing Pin Safety & Manual Safety",
      EffectiveRange: "25 m",
      FrameMaterial: "Polymer",
    },
  },

  { name: "ARMO V4", 
    description: " 9 mm polymer-framed, stiker-fired pistol designed for Military and Law Enforcement use.", 
    image: "ARMO V4.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "16 rounds",
      FiringMode: "Semi Automatic (Hammerless/Striker–Fired)",
      Action: "Double Action",
      Weight: "0,85 kg",
      OverallLength: "212 mm",
      BarrelLength: "118 mm",
      Sight: "Fixed Front & Rear Sight",
      Safety: "Firing Pin Safety & Manual Safety",
      EffectiveRange: "25 m",
      Rifling: "6 Grooves RH, 254 mm/twist",
      FrameMaterial: "Polymer",
    },
  },

  /* SUB MACHINE GUNS */
  { name: "PM3", 
    description: " A high-performance gas operated 9 mm submachine gun for Military and Law Enforcement use ", 
    image: "PM3.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "30 rounds (MP5 Magazine)",
      OperatingPrinciple: "Gas Operated",
      Weight: "3,27 ± 0,2 kg",
      OverallLength: "776 ± 5 mm",
      BarrelLength: "210 ± 0,8 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "75 m",
      Rifling: "6 Grooves RH, 250 mm (10”)/Twist",
      RateOfFire: "780-850 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "PM3-V3", 
    description: " 9 mm Pistol Caliber Carbine designed to win shooting competitions", 
    image: "PM3-V3.png",
     specifications: {
      Caliber: "9 x 19 mm",
      MagazineCapacity: "30 rounds (Pistol Magazine)",
      OperatingPrinciple: "Gas Operated",
      Weight: "3,26 ± 0,2 kg",
      OverallLength: "805 ± 5 mm",
      BarrelLength: "210 ± 0,8 mm",
      Sight: "Fixed Front Iront Sight and Rear Iron Sight",
      Safety: "Selector Switch",
      EffectiveRange: "75 m",
      Rifling: "6 Grooves RH, 250 mm (10”)/Twist",
      FiringMode: "Semi Automatic",
    },
  },

  { name: "SB2-V5 A1", 
    description: "  A gas operated .222 CQB rifle for Special Law Enforcement Units.", 
    image: "SB2-V5 A1.png",
     specifications: {
      Caliber: "222",
      MagazineCapacity: "20 rounds",
      OperatingPrinciple: "Gas Operated",
      Weight: "3,69 kg",
      OverallLength: "799 mm",
      BarrelLength: "253,4 mm",
      Sight: "Flip Up Iron Sights",
      Safety: "Selector Switch",
      EffectiveRange: "200 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      FiringMode: "Safe, Semi Automatic",
    },
  },

  /* SNIPER RIFLES */
  { name: "SPM-1", 
    description: " 5.56 mm gas operated rifle for Military use specifically designed and tuned for Designated Marksman Rifle (DMR) role with advanced modularity and ergonomy. Based on the successful SS2 platform, tested and qualified on the most demanding battlefield conditions.  ", 
    image: "SPM-1.png",
    specifications: {
      Caliber: "5,56 x 45 mm",
      MagazineCapacity: "20 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "3,8 kg",
      OverallLength: "1.008 mm",
      BarrelLength: "18”",
      Sight: "Mechanical (Flip Up) and Optical (1-8x)",
      Safety: "Selector Switch",
      EffectiveRange: "400 m (Mechanical Sight), 600 m (Optical Sight)",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "720-900 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: "SPM-2", 
    description: " 7.62 mm gas operated rifle for Military use specifically designed and tuned for Designated Marksman Rifle (DMR) role with advanced modularity and ergonomy. Based on the new platform created by PT Pindad. ", 
    image: "SPM-2.png",
    specifications: {
      Caliber: "7,62 x 51 mm",
      MagazineCapacity: "20 rounds",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "5,3 kg",
      OverallLength: "1.070 mm",
      BarrelLength: "510 mm",
      Sight: "Mechanical (Flip Up) and Optical (1-8x)",
      Safety: "Firing Mode Selector Lever",
      EffectiveRange: "400 m (Mechanical Sight), 600 m (Optical Sight)",
      Rifling: "6 Grooves RH, 304,8 mm/Twist",
      RateOfFire: "720-820 round/minute",
      FiringMode: "Safe, Semi Automatic, Full Automatic",
    },
  },

  { name: " SPR-2 ", 
    description: " 12,7 mm/.50 BMG bolt-action precision rifle for Military use, specifically designed for long-range target engagement. Tuned by PT Pindad to achieve superior accuracy using special 12.7 mm/.50 BMG  ammunition manufactured by PT Pindad including HEI-AP, LRSA, and Sniper Anti Material.", 
    image: "SPR-2.png",
    specifications: {
      Caliber: "12,7 x 99 mm",
      MagazineCapacity: "5 rounds",
      OperatingPrinciple: "Bolt Action / Repeater",
      EmptyWeight: "17,68 kg",
      OverallLength: "1.762 mm",
      BarrelLength: "1.055 mm",
      Sight: "Optical Sight",
      EffectiveRange: "2.000 m",
      Rifling: "6 Grooves RH, 381 mm/ Twist",
      FiringMode: "Single Shot",
    },
  },

  { name: " SPR-3 ", 
    description: " 7,62 mm/.308 WIN bolt-action precision rifle for Military use, specifically designed for long-range target engagement. Tuned by PT Pindad to achieve superior accuracy using special 7.62 mm/.308 WIN  ammunition manufactured by PT Pindad including Sniper, Match, and Match King", 
    image: "SPR-3.png",
    specifications: {
      Caliber: "7,62 x 51 mm",
      MagazineCapacity: "10 rounds",
      OperatingPrinciple: "Bolt Action / Repeater",
      EmptyWeight: "7,9 kg",
      OverallLength: "1.230 mm",
      BarrelLength: "600 mm",
      Sight: "Optical Sight",
      EffectiveRange: "900 m",
      Rifling: "4 Grooves RH, 304,8 mm/ Twist",
      FiringMode: "Single Shot",
    },
  },

  { name: " SPR-4 ", 
    description: ".338 LM bolt-action precision rifle for Military use, specifically designed for long-range target engagement. Tuned by PT Pindad to achieve superior accuracy using special .338 LM ammunition manufactured by PT Pindad.", 
    image: "SPR-4.png",
    specifications: {
      Caliber: "338",
      MagazineCapacity: "5 rounds",
      OperatingPrinciple: "Bolt Action",
      EmptyWeight: "8,25 kg",
      OverallLength: "1.298 mm",
      BarrelLength: "658,8 mm",
      Sight: "Optical Sight",
      EffectiveRange: "1.500 m",
      Rifling: "6 Grooves RH, 254 mm/ Twist",
      FiringMode: "Single Shot",
    },
  },

  /* MACHINE GUNS */
  { name: " SM2-V1 ", 
    description: " 7,62 mm General Purpose Machine Gun for Military use designed for sustained fire by infantry units.", 
    image: "SM2-V1.png",
    specifications: {
      Caliber: "7,62 x 51 mm",
      FeedingSystem: "Link Belt",
      OperatingPrinciple: "Operated",
      EmptyWeight: "11,6 kg",
      OverallLength: "1.260 mm",
      BarrelLength: "545 mm",
      Sight: "Iron Sights",
      EffectiveRange: "1.000 m",
      Rifling: "4 Grooves RH, 304,8 mm/Twist",
      RateOfFire: "650 – 1000 round/minute",
      FiringMode: "Full Automatic ",
    },
  },

  { name: " SM2-V2 ", 
    description: "7,62 mm General Purpose Machine Gun for Military use designed for sustained fire from military vehicles.", 
    image: "SM2-V2.png",
    specifications: {
      Caliber: "7,62 x 51 mm",
      FeedingSystem: "Link Belt",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "12 kg",
      OverallLength: "1.070 mm",
      BarrelLength: "587 mm",
      Sight: "Iron Sights",
      EffectiveRange: "1.000 m",
      Rifling: "4 Grooves RH, 304,8 mm/Twist",
      RateOfFire: "700 – 1200 round/minute",
      FiringMode: "Full Automatic",
    },
  },

  { name: " SM3 ", 
    description: " 5,56 mm Light Machine Gun/Squad Automatic Weapon for Military use designed for sustained fire by infantry units.", 
    image: "SM3.png",
    specifications: {
      Caliber: "5,56 x 45 mm",
      FeedingSystem: "Link Belt",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "6,90 kg",
      OverallLength: "1.047 mm",
      BarrelLength: "466 mm",
      Sight: "Iron Sights",
      EffectiveRange: "600 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "700 – 1.000 round/minute",
      FiringMode: "Full Automatic",
    },
  },

  { name: " SM3-A1 ", 
    description: " 5,56 mm Light Machine Gun/Squad Automatic Weapon for Military use designed for sustained fire by infantry units with additional features WEAPONS including adjustable buttstock and the ability to feed from NATO 30 round magazine.", 
    image: "SM3-A1.png",
    specifications: {
      Caliber: "SM3-A1",
      FeedingSystem: "Link Belt and Magazine",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "7,6 kg",
      OverallLength: "1.072 mm",
      BarrelLength: "466 mm",
      Sight: "Iron Sights",
      EffectiveRange: "600 m",
      Rifling: "6 Grooves RH, 177,8 mm/Twist",
      RateOfFire: "700 – 1.200 round/minute",
      FiringMode: "Full Automatic",
    },
  },

  { name: " SM5 ", 
    description: " gas operated 12,7 mm/.50 BMG Heavy Machine Gun for Military use designed for sustained fire from various platforms: military vehicles, military vessels, or infantry use with tripod.", 
    image: "SM5.png",
    specifications: {
      Caliber: "12,7 x 99 mm",
      FeedingSystem: "Link Belt",
      OperatingPrinciple: "Gas Operated",
      EmptyWeight: "34 kg",
      OverallLength: "1.688 mm",
      BarrelLength: "1.141 mm",
      Sight: "Iron Sights",
      EffectiveRange: "1.830 m",
      Rifling: "8 Grooves RH, 1:15” (381 mm/Twist)",
      RateOfFire: "400 – 650 round/minute",
      FiringMode: "Full Automatic",
    },
  },

  { name: " SM5-A1 ", 
    description: " blowback 12,7 mm/.50 BMG Heavy Machine Gun for Military use designed for sustained fire from various platforms: military vehicles, military vessels,  or infantry use with tripod.", 
    image: "SM5-A1.png",
    specifications: {
      Caliber: "12,7 x 99 mm",
      FeedingSystem: "Link Belt",
      OperatingPrinciple: "Blowback/Short Recoil",
      EmptyWeight: "39 kg",
      OverallLength: "1.697 mm",
      BarrelLength: "1.110 mm",
      Sight: "Iron Sights",
      EffectiveRange: "1.800 m",
      Rifling: "8 Grooves RH, 1:15” (381 mm/Twist)",
      FiringMode: "Full Automatic",
    },
  },

  /* GRENADE LAUNCHERS */
  { name: " SAR-2 ", 
    description: " 38 mm non-lethal launcher for Law Enforcement use designed to fire various 38 mm cartridges including tear gas, smoke, and rubber balls", 
    image: "SAR-2.png",
    specifications: {
     Caliber: "38 mm",
     OperatingPrinciple: "Manual",
     Weight: "2,36 kg",
     OverallLength: "763 mm",
     BarrelLength: "360 mm",
     Sight: "Mechanical",
     MaximumRange: "125 m",
     FiringMode: "Single Shot",
    },
  },

  { name: " SPG1A-V2 ", 
    description: "40 mm grenade launcher for Military use designed to fire various 40 mm Low Velocity Grenades including High Explosive and Smoke. Attachable to SS1 Assault Rifle", 
    image: "SPG1A-V2.png",
    specifications: {
     Caliber: "40 mm",
     OperatingPrinciple: "Break Open",
     FeedingSystem: "Manual",
     Weight: "1,8 kg",
     TriggerPull: "2,7 kg",
     OverallLength: "394 mm",
     BarrelLength: "305 mm",
     Sight: "Mechanical",
     MaximumRange: "350 m",
     Rifling: "6 Grooves RH, 1225 mm (5°55’)",
     MuzzleVelocity: "75 m/s",
     FiringMode: "Single Shot",
    },
  },

  { name: " SPG1A-V3 ", 
    description: "40 mm grenade launcher for Military use designed to fire various 40 mm Low Velocity Grenades including High Explosive and Smoke. Attachable to SS2-V5 Short-Barreled Assault Rifle.", 
    image: "SPG1A-V3.png",
    specifications: {
    Caliber: "40 mm",
     OperatingPrinciple: "Break Open",
     FeedingSystem: "Manual",
     Weight: "1,2 kg",
     TriggerPull: "2,7 kg",
     OverallLength: "298 mm",
     BarrelLength: "200 mm",
     Sight: "Mechanical",
     MaximumRange: "350 m",
     Rifling: "6 Grooves RH, 1225 mm (5°55’)",
     MuzzleVelocity: "75 m/s",
     FiringMode: "Single Shot",
    },
  },

  { name: " SPG1A-V4 ", 
    description: "40 mm grenade launcher for Military use designed to fire various 40 mm Low Velocity Grenades including High Explosive and Smoke. Attachable to SS2-V4 Assault Rifle.", 
    image: "SPG1A-V4.png",
    specifications: {
    Caliber: "40 mm",
     OperatingPrinciple: "Break Open",
     FeedingSystem: "Manual",
     Weight: "1,7 kg",
     TriggerPull: "2,7 kg",
     OverallLength: "419 mm",
     BarrelLength: "305 mm",
     Sight: "Mechanical",
     MaximumRange: "350 m",
     Rifling: "6 Grooves RH, 1225 mm (5°55’)",
     MuzzleVelocity: "75 m/s",
     FiringMode: "Single Shot",
    },
  },

  /* ANTI DRONE SYSTEM */
  { name: " SPS-1 ANTI DRONE ", 
    description: " A man-portable handheld Anti Drone System with Soft Kill and Hard Kill capability. Able to neutralize enemy drones from 100 m range using Hard Kill feature.", 
    image: "SPS-1 ANTI DRONE.png",
    specifications: {
      softkill:{
        WorkingFrequency:"GNSS, Remote Control dan Video Transmitter",
        ShootingAngle:"± 80º",
        WorkingVoltage:"12 V",
        WorkingTime:"60 Minutes (Continues)",
        BatteryCapacity:"10000 mAh",
        BatteryType:"3S Li Ion",
      },
      hardkill:{
        Caliber:"5,56 x 45 mm",
        Ammunition:"MU5-TJ and other similar items",
        MagazineCapacity:"30 rounds",
        EffectiveRange:"100 m (Linear)",
      },
    },
  },

  { name: "MOBILE JAMMER SECTORIAL MOBILE JAMMER", 
    description: " An integrated Mobile Anti Drone System with Soft Kill and Hard Kill capability. Able to neutralize enemy drones within 3 km radius using Soft Kill feature.", 
    image: "MOBILE JAMMER SECTORIAL MOBILEJAMMER.png",
    specifications: {
      softkill: {
        WorkingFrequency:"GNSS, Remote Control dan Video Transmitter",
        WorkingVoltage:"220 VAC / 50 Hz",
        PowerConsumption:"700 Watt",
        JammerRange:"Up to 3 Km (radius)",
      },
      hardkill: {
        Armament:"SM5-A1 Heavy Machine Gun",
        Caliber:"12,7 x 99 mm",
        Ammunition:"MU3-P Link HBFL and other similar ammunitions",
        FeedingMechanism:"Belt",
      },

      specifications: {
        softkill: {
          WorkingFrequency:"GPS, Remote Control dan Video Transmitter",
          WorkingVoltage:"220 VAC / 50 Hz",
          PowerConsumption:"700 Watt",
          JammerRange:"Up to 3 Km (radius)",
          Material:"Unsaturated Polyester Resin, Alumunium",
        },
      },
    },
  },

  { name: " Mo-1 ", 
    description: " 60 mm Commando Mortar Launcher for Military use designed for attacking short range enemy positions.", 
    image: "Mo-1.png",
    specifications: {
      Caliber:"60 mm CO",
      TotalWeight:"6,65 kg",
      OverallLength:"570 mm",
      BarrelLength:"399,5 mm",
      MaximumRange:"800 m",
    },
  },

  { name: " Mo-2 ", 
    description: "60 mm Long Range Mortar Launcher for Military use designed for attacking long range enemy positions.", 
    image: "Mo-2.png",
    specifications: {
      Caliber:"60 mm LR",
      TotalWeight:"18,3 kg",
      OverallLength:"945 mm",
      BarrelInnerDiameter:"60,6 mm",
      Sight:"Mechanical",
      Elevation:"42° - 85°",
      MaximumRange:"4.000 m",
      FiringMechanism:"Drop",
    },
  },

  { name: " Mo-3 ", 
    description: " 81 mm Mortar Launcher for Military use designed for attacking long range enemy positions. ", 
    image: "Mo-3.png",
    specifications: {
      Caliber:"81 mm",
      TotalWeight:"55,2 mm",
      SightAccuracy:"1 mil",
      OverallLength:"1.600 mm",
      BarrelInnerDiameter:"81,36 mm",
      Sight:"Mechanical",
      Elevation:"42° - 85°",
      MaximumRange:"6.500 m",
      FiringMechanism:"Drop",
    },
  },

  { name: " SHIELD REMOTE CONTROLLED WEAPON STATION (RCWS) ", 
    description: " A modular Remote Controlled Weapon Station designed to provide firepower as well as protection to vehicle crew members. Able to use 7,62 mm and 12,7 mm using single cradle. Equipped with day and thermal camera with long Detection, Recognition, and Identification range as well as target locking and tracking features.", 
    image: "SHIELD REMOTE CONTROLLED WEAPON STATION (RCWS).png",
    specifications: {
       Armament:"12,7 mm Machine Gun = SM5 - 7,62 mm Machine Gun = SM2-V2",
       AmmunitionCapacity:"12,7 mm Machine Gun = 260 rounds - 7,62 mm Machine Gun = 600 rounds ",
       Dimension:"1.266 x 1.068 x 753 mm",
       Weight:"200 kg (without weapon and ammunition)",
       Azimuth:"360°",
       Elevation:"+60° s.d. -20°",
       Stability:"2 Axis Gyro Aided Stabilization",
       DayCamera:"1920 x 1080, 32x Optical Zoom",
       ThermalCamera:"640 x 480, Uncooled",
       LaserRangeFinder:"1570 µm, Eye Safe (Class-1)",
       Monitor:"LCD Monitor 15”, 1920 x 1080",
    },
  },
];
  
const SenjataPage = () => {
  const [selectedItem, setSelectedItem] = useState(null);
  const navigate = useNavigate();

  return (
    <section className="container mx-auto pt-20 py-10 px-4">
      <h2 className="text-3xl sm:text-4xl font-bold text-center mb-6">Weapon</h2>

      <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {senjata.map((item, index) => (
          <div key={index} className="bg-white shadow-lg rounded-lg overflow-hidden">
            
            {/* Centering the image */}
            <div className="flex justify-center pt-4">
              <img
                src={`/images/senjata/${item.image}`}
                alt={item.name}
                className="w-82 h-32 object-cover rounded-md"
                onClick={() => setSelectedItem({ ...item, showImage: true })}
              />
            </div>
        
            <div className="p-3 sm:p-4 text-center">
              <h3 className="text-sm sm:text-base font-semibold">{item.name}</h3>
              <button
                className="mt-2 px-3 py-1 sm:px-4 sm:py-2 bg-blue-500 text-white text-sm sm:text-base rounded hover:bg-blue-700"
                onClick={() => setSelectedItem({ ...item, showImage: false })}
              >
                Desc
              </button>
              {/* Tombol Spesifikasi */}
                <button
                  className="mt-2 px-3 py-1 sm:px-4 sm:py-2 bg-green-500 text-white text-sm sm:text-base rounded hover:bg-green-700"
                  onClick={() => navigate(`/senjata/${encodeURIComponent(item.name)}`)}
                >
                Spesifikasi
              </button>
            </div>
          </div>
        ))}
      </div>


      {/* Modal Gambar */}
      {selectedItem && selectedItem.showImage && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center p-4 z-50">
          <div className="bg-white p-4 rounded-lg shadow-lg max-w-xl w-full">
            <img
              src={`/images/senjata/${selectedItem.image}`}
              alt={selectedItem.name}
              className="w-full h-auto rounded"
            />
            <button
              className="mt-4 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-700 block mx-auto"
              onClick={() => setSelectedItem(null)}
            >
              Close
            </button>
          </div>
        </div>
      )}

      {/* Modal Deskripsi */}
      {selectedItem && selectedItem.showImage === false && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center p-4 z-50">
          <div className="bg-white p-5 sm:p-6 rounded-lg shadow-lg w-full max-w-xs sm:max-w-sm text-center">
            <h3 className="text-lg sm:text-xl font-semibold mb-2">{selectedItem.name}</h3>
            <p className="text-gray-600 text-sm sm:text-base">{selectedItem.description}</p>
            <button
              className="mt-4 px-3 py-1 sm:px-4 sm:py-2 bg-red-500 text-white text-sm sm:text-base rounded hover:bg-red-700"
              onClick={() => setSelectedItem(null)}
            >
              Close
            </button>
          </div>
        </div>
      )}
    </section>
  );
};

export { senjata };
export default SenjataPage;
  